### ISSUE TITLE
shell-x64.dll broken in latest 0.12.7 version.

### ISSUE THREAD

**Issue by inkarkat** [xolox/vim-shell#13]
After upgrading to vim-shell 0.12.7, I get the following error on GVIM startup on Windows/x64, caused by the easytags plugin:

```
Error detected while processing function <SNR>259_InitEasyTags..<SNR>259_CheckCtags..xolox#misc#os#exec..xolox#shell#execute_with_dll:
line   12:
E605: Exception not caught: execute_synchronous('C:\Windows\system32\cmd.exe /c (ctags --version) 1>"D:\TEMP\VIA8873.tmp" 2>"D:\TEMP\VIB8874.tmp"') failed! (output: exit_cod)
```

(The last character of the output is U+0080 PADDING CHARACTER!)

This can then be reproduced with other calls to `xolox#misc#os#exec()`. The problem does not occur with a 32-bit GVIM on the same system; downgrading to the previous commit of `shell-x64.dll` also fixes the problem, so the issue seems to be related to the latest build of that DLL.

I'm on Windows 7 Ultimate SP1 English 64-bit, and can reproduce this on 2 different systems, and using both a self-compiled Vim 7.3.823/x64 as well as with the old 7.3.000 64-bit build provided by George Reilly.

Please let me know if you need any other information. Thanks!

**Comment by xolox** [comment]
I use a Windows Batch script to build the DLLs so that most likely excludes me screwing up a manual build. Unfortunately I don't have a 64 bit Windows environment so I can't test the x64 DLL :-(. You don't happen to have a build environment set up to compile against the Windows API and some programming experience with the Windows API? ;-)

I'm not actually sure if I screwed up the build or if my code changes in 653918545629ef553ee46214714c9177283fc0a6 (tagged as 0.12) are the problem. It may very well be the code changes. However I can't easily test or verify this. I have some ideas though:
- Maybe `sprintf()` is simply not to be used on 64 bit machines.
- Maybe the format specifier for the exit code is wrong (`%li` as in a long integer, which is dependent on bitness so this sounds like it might be related).
- Maybe this is related to ANSI vs. Unicode (really UTF-16 IIUC) builds.

I'll see if I can get my hands on a 64 bit Windows environment to make it easier to confirm my suspicions.

**Comment by xolox** [comment]
Some research notes:
- `DWORD exit_code` → [32 bit unsigned integer](http://msdn.microsoft.com/en-us/library/cc230318.aspx)
- According to the [printf Type Field Characters](http://msdn.microsoft.com/en-us/library/hf4y5e3w%28v=vs.71%29.aspx) `%i` is for signed integers while `%u` is for unsigned integers
- According to the [Size and Distance Specification](http://msdn.microsoft.com/en-us/library/tcxf1dw6%28v=vs.71%29.aspx) `%li` specifies a signed long integer which certainly doesn't match the `DWORD` → [32 bit unsigned integer](http://msdn.microsoft.com/en-us/library/cc230318.aspx) note above...

This can certainly be improved. Let me get back to you :-)

**Comment by xolox** [comment]
Can you try out the latest release on GitHub (not yet on Vim Online) to confirm whether my change in aac1374 resolves the problem? If it does, I'll release to Vim Online as well.
