### ISSUE TITLE
Query Strings in urls for :Open?

### ISSUE THREAD

**Issue by brycefisher** [xolox/vim-shell#22]
I'm running gvim 7.3 with vim-shell and vim-misc on Windows 7. The `:Open` command works great for urls without query strings, but I'd like to create mappings that yank the current word and start a search query on duckduckgo and jquery. They use **?s=** and **?q=** to start queries. 

Here's a screenshot of my mapping and the error I'm getting with Vim:
![image](https://f.cloud.github.com/assets/220106/1018680/358c2116-0c2f-11e3-81b0-0b88f7ce3446.png)

Here's the mapping in text format:

```
"Search JQuery API Docs online against the word under cursor
nnoremap <Leader>jqa "zyw:exec "Open http://api.jquery.com/?s=".@z<CR>

"Jump start a DuckDuckGo Search 
nnoremap <Leader>ddg :Open http://duckduckgo.com/?q=
```

Is it possible to get `:Open` to recognize these as urls?

**Comment by xolox** [comment]
If I type out the following command in Vim's interactive command mode:

``` vim
:Open http://duckduckgo.com/?q=vim-shell
```

It works fine and the expected page is opened. So vim-shell / the `:Open` command are not changing the meaning of the question marks; it's somewhere else in Vim.

The error in the screenshot is clearly about the example involving the jQuery API search, however I don't understand most of what's on that line (the `"zyw:exec "` stuff which doesn't make any sense to me without further context). I can provide one hint: If I try the Vim command `:help e480` I end up in the help entry for `:argdelete` which is not at all related to what you want to do. I guess the command involving the jQuery API search is being interpreted very differently from what you want it to do...

One last bit of advice, feel free to completely ignore it if you're not interested: When I end up in this kind of confusion about what a Vim command is doing, I usually decide to extract it out into a user defined function and call that user defined function from my custom mapping.

I'm closing this issue because I don't see how this is a bug in vim-shell, however if you have further questions feel free to post them here; I'll do my best to help you out. Also, if you can show me how vim-shell is making a mistake here I'm open to fixing it, but as I showed at the top of my post that doesn't seem to be the case.

**Comment by majkinetor** [comment]
I have this very same problem. Calling a function works fine but command reports `E480 No match` error.

After debugging it shows that it boils down to `-complete=file` parameter of `command! -bar -nargs=? -complete=file Open call xolox#shell#open_cmd(<q-args>)`. Removing it doesn't produce that error.  This behavior is happening only in Windows here. 

I don't know why is this happening. This also produces error with `?` char

<pre>
command! -complete=file -nargs=? Echo echo 
Echo http://www.google.com/search?q=foo
</pre>

I did run vim with `-u NONE` option and this still happens. It stops happening when `-nargs=*` 

So to fix this you need to put this kind of command:

`command! -complete=file -bar -nargs=* Open call xolox#shell#open_cmd(<q-args>)`

or

`command! -bar -nargs=? Open call xolox#shell#open_cmd(<q-args>)`

**Comment by brycefisher** [comment]
Thanks, majkinetor!
