### ISSUE TITLE
There is no function xolox#misc#option#get

### ISSUE THREAD

**Issue by ensonmj** [xolox/vim-shell#3]
Hi
I use vundle to manage my plugins and clone vim-shell and vim-easytags in seperate folds in "vimfiles/", then vim tell me undefined function "xolox#misc#option#get". When I comment "Bundle vim-shell", this error message won't appear. 
And then I found "...\vim-shell\autoload\xolox\misc\option.vim" has no funtion "get".
Would you please update that?

**Comment by Valloric** [comment]
I have this exact same problem.

**Comment by Valloric** [comment]
I also have xolox/vim-session in my vim config. The problem is that the "...\autoload\xolox\misc\option.vim" from vim-shell OR vim-session is loaded BEFORE the option.vim file in easytags. And both of those option.vim files don't have the "get" function, so easytags ends up throwing an error.

The solution is to update the option.vim file in vim-shell and vim-session. And may I suggest that in the future, you make your vim-misc plugin a requirement of vim-shell and vim-session instead of just bundling it inside those two plugins. It would prevent these kinds of problems in the future.

**Comment by xolox** [comment]
Hi ensonmj and Valloric,

Sorry about taking a while to reply & fix this. I've now updated the vim-shell, vim-easytags and vim-session repositories to include the latest version of vim-misc. In the future when I update vim-misc, I will make sure to update all depending repositories as well (preferably automatically but we'll see about that).
