### ISSUE TITLE
Doesn't open URLs from Apple mail.app

### ISSUE THREAD

**Issue by jlmaccal** [xolox/vim-shell#5]
I'm running into a problem where the Open command isn't getting the correct URL. I think the problem is that the URLs for message links have a % sign in them.

The link should be:

message://%3cCAC1F077.18CFC%larry.schweitzer@ucsf.edu%3e

Calling :Open on this tells mail to open:

message://%253cCAC1F077.18CFC%25larry.schweitzer@ucsf.edu%253e

Mail doesn't know how to open this due to the spurious %25's.

**Comment by xolox** [comment]
I'm not sure what to make of this. Clearly something is performing a double encode of the URL in question:
- `%3c` and `%3e` stand for `<` and `>`
- `%25` stands for `%`

However the shell plug-in doesn't contain any code to perform URL encoding, which makes sense because why should it? It doesn't generate new URLs, it just follows existing URLs. Anyway I just published a new release with some debugging statements. To see the debugging messages please execute the following Vim command:

```
:set verbose=1
```

After this when you press `<F6>`, one or more messages will be printed to Vim's message buffer. If the messages disappear from the screen you can recall the message history using the following Vim command:

```
:messages
```

I'm guessing the printed messages will indicate that the shell plug-in is not the one performing the double URL encoding... Of course then we still have to find out where the double URL encoding is happening so that you can properly follow hyper links to e-mail messages (fancy feature by the way, I've considered doing the same but the URLs generated by Mozilla Thunderbird are so god awfully long that I decided against it :-).

**Comment by xolox** [comment]
Closing old issues. If this is still relevant please reopen.
