### ISSUE TITLE
shellslash setting

### ISSUE THREAD

**Issue by punassuming** [xolox/vim-shell#6]
If I set shellslash in my vimrc for both linux and windows environments (I like uniform front slashes everywhere, even windows). I get this error when starting up with easytags on windows:

shell.vim 0.9.13: Failed to get output of command "C:\Windows\system32\cm
d.exe /c ctags --version > 'C:/Users/walesi/AppData/Local/Temp/VIA9EB2.tm
p' 2>&1"! at function <SNR>49_InitEasyTags..<SNR>49_CheckCtags..xolox#sh
ell#execute, line 32

easytags.vim 2.7: Plug-in not loaded because Exuberant Ctags isn't installed! 
Please download & install Exuberant Ctags from http://ctags.sf.net

It all comes down to the part in autoload/xolox/shell.vim with the shellescape()

105    if a:synchronous
106     let tempout = tempname()
107      let cmd .= ' > ' . shellescape(tempout) . ' 2>&1'
108    endif

The double quotes from the shellescape() are what make the temp file access impossible in the execute command.  I can fix the problem by removing the shellescape, but I don't know if that is the only way

**Comment by xolox** [comment]
> The **double quotes** from the shellescape() are what make the temp file access impossible in the execute command. I can fix the problem by removing the shellescape, but I don't know if that is the only way

I guess you meant to say single quotes?

The problem is that Vim's ['shellslash'](http://vimdoc.sourceforge.net/htmldoc/options.html#%27shellslash%27) setting controls more than just the type of slashes used in filenames; as you found out it also controls whether command line arguments to external commands are quoted with double quotes (the default on Windows) or single quotes. However single quotes are never a valid quoting mechanism in the default Windows shell `CMD.EXE` -- single quotes only work if you use a UNIX style shell under Windows (don't ask me why but some people do this -- I've never tried it).

I've had previous reports about this issue. Maybe the shell plug-in should just temporarily reset the 'shellslash' option during its execution and restore the original user defined value afterwards. IIUC you should never notice the difference except that the shell plug-in will actually work out of the box :-).

**Comment by xolox** [comment]
Hi Rich,

I just published a new version of the vim-shell plug-in that should fix the issue you reported. If you try it out please let me know whether it resolves the issue for you.

 - Peter

**Comment by xolox** [comment]
Closing old issues. If this is still a problem feel free to reopen this issue.
