### ISSUE TITLE
Open & Fullscreen focus

### ISSUE THREAD

**Issue by mMontu** [xolox/vim-shell#9]
When Vim is not in fullscreen and `:Open` is executed the external application (file browser, web browser) opens in front of Vim and get the focus - which I believe is the expected behavior, as you'd normally use the application that was just started.

But if `:Fullscreen` is executed before `:Open` then the external application opens but Vim retains the focus. Is there an option to make the external application to get the focus?

**Comment by xolox** [comment]
In the latest version WS_EX_TOPMOST can now be disabled using the [g:shell_fullscreen_always_on_top](http://peterodding.com/code/vim/shell/#shell_fullscreen_always_on_top_option) option but Alt-Tab does not work for me. Please try it out and let me know whether this works for you.

**Comment by mMontu** [comment]
I've tried `let g:shell_fullscreen_always_on_top = 0` and noticed some changes in the behavior, but issuing `Open` while in Fullscreen still displays gVim, while the focus seems to change to the hidden file browser. 

Alt-Tab doesn't work for me neither.

I've tested this on windows xp.

**Comment by xolox** [comment]
A peek inside the "Vim plug-in design" process in my brain:
- Since `:Open` and `:Fullscreen` are both defined by the same plug-in it might be fair game if `:Open` takes Vim out of full screen... Would that be an improvement?
  - I'm trying to balance in my head the number of people bothered by the behavior reported in this issue vs. the number of people bothered by `:Open` taking Vim out of full screen.
    - I could of course add an option for that.
      - I'm always bothered when my plug-ins cannot decide on "the best" defaults by themselves :-(
  - _This actually kind of feels like a huge hack that shouldn't be necessary in the first place..._
- I could take another stab at fixing the issue originally reported by changing the compiled C code
  - But then I have to spend a lot of time inside Windows which I haven't done in over three years and nowadays I'm spoiled by Linux and Mac OS X both being proper UNIX environments (nice terminals, awesome command line tools, most things can be scripted, etc.)
  - This also implies an awkward edit/compile/restart/test cycle which can't really be helped
  - I am _not_ an experienced Windows API programmer (actually I haven't touched it in a long time)

While working on this answer and considering my options I decided to take another quick stab at fixing the Windows API code and it worked! I can now full screen my Vim on Windows XP while being able to Alt-Tab to other programs. `:Open` also focuses the newly started program when [g:shell_fullscreen_always_on_top](http://peterodding.com/code/vim/shell/#shell_fullscreen_always_on_top_option) is set to 0 (false).

I'm closing this issue now as the problem should be resolved. If it's not, feel free to reopen the issue. Thanks for the bug report and making `vim-shell` better :-).

**Comment by mMontu** [comment]
Both Alt-Tab and focus are working very well for me!
I've tested it on Windows XP and 7.

There is only one minor problem: when gVim window is maximized and one calls `:Fullscreen` twice, the resulting window is not maximized anymore.
